Load interpreter segments with correct perms and vaddr
qilingframework/qiling pull request #1120
Opened 2022-03-26 12:20 UTC by bet4it

## Checklist

### Which kind of PR do you create?

- [x] This PR only contains minor fixes.
- [ ] This PR contains major feature update.
- [ ] This PR introduces a new function/api for Qiling Framework.

### Coding convention?

- [x] The new code conforms to Qiling Framework naming convention.
- [x] The imports are arranged properly.
- [x] Essential comments are added.
- [x] The reference of the new code is pointed out.

### Extra tests?

- [x] No extra tests are needed for this PR.
- [ ] I have added enough tests for this PR.
- [ ] Tests will be added after some discussion and review.

### Changelog?

- [ ] This PR doesn't need to update Changelog.
- [x] Changelog will be updated after some proper review.
- [ ] Changelog has been updated in my PR.

### Target branch?

- [x] The target branch is dev branch.

### One last thing

- [x] I have read the [contribution guide](https://docs.qiling.io/en/latest/contribution/)

-----

We loaded all the segments of `ld` with `rwx` previously.

2022-03-27 13:19 UTC, elicn requested changes
Nice work!

2022-03-27 13:19 UTC, elicn commented on qiling/loader/elf.py
> +        def load_elf_segments(self, elffile: ELFFile, load_address: int, info: str):
This is an internal function, not an instance method, so no need to pass `self` as an arg.
The function can use `self` from the outter scope if needed.

2022-03-27 13:19 UTC, elicn commented on qiling/loader/elf.py
> +                interp_address = int(self.profile.get('interp_address'), 0) if min_vaddr == 0 else 0
Would appreciate a brief comment explaining the rationale the way `interp_address` is selected.

2022-04-04 06:31 UTC, elicn approved these changes

2022-04-04 07:51 UTC, kabeor approved these changes

2022-04-04 07:53 UTC, merged