fix mcu issue in qdb and show flags with color BLUE in uppercase, oth…
qilingframework/qiling pull request #1263
Opened 2022-10-25 15:20 UTC by ucgJhe

1. fix #1262 
2. more intuitive way for displaying flags

![image](https://user-images.githubusercontent.com/10076774/197814334-df8ca152-f359-4a57-b739-633c5a9a71fb.png)

2022-10-25 18:56 UTC, elicn requested changes

2022-10-25 18:56 UTC, elicn commented on qiling/arch/cortex_m_const.py
> +    "cpsr":      UC_ARM_REG_CPSR,
That is not a good idea... If you decide to go with a temporary solution, then we should do this in a different way. I suggest to do that by modifying render_arm.py line 34:
```python
# there is no cpsr in cortex m
if 'cpsr' in self.ql.arch.regs.register_mapping:
    self.print_mode_info(self.ql.arch.regs.cpsr)
```

2022-11-10 05:21 UTC, xwings commented
@ucgJhe will you be able to update the code ?

2022-11-10 12:47 UTC, ucgJhe commented
@xwings will still break something, i think this can wait until we fix #1265

2022-11-10 13:41 UTC, xwings commented
We need @elicn help for that,

2022-11-11 07:37 UTC, xwings commented
@ucgJhe i merge Eli's PR. Will you be able to try ?

2022-11-12 15:30 UTC, ucgJhe commented
looks good now

2022-11-12 15:33 UTC, ucgJhe commented
new question, Im not sure is this normal ? stack pointer will point to a non-existence value

![image](https://user-images.githubusercontent.com/10076774/201481577-b3f53740-4945-4624-971f-8609d230073c.png)

2022-11-23 14:50 UTC, elicn commented
Hey @ucgJhe , what keeps us from merging this one?
I think once the `cpsr` addition to CORTEX_M is reverted, we're good to go.

2022-11-24 03:39 UTC, ucgJhe commented
> Hey @ucgJhe , what keeps us from merging this one? I think once the `cpsr` addition to CORTEX_M is reverted, we're good to go.

It's all good to go. ping @xwings

2022-11-24 08:27 UTC, kabeor approved these changes

2022-11-28 09:31 UTC, elicn approved these changes

2022-11-28 09:32 UTC, merged