Fix directory traversal bug (replacement of #574)
qilingframework/qiling pull request #579
Opened 2020-11-12 16:02 UTC by nmantani

Hi,

I improved handling of Windows UNC paths of normalize() in qiling/os/utils.py
and added tests/test_pathutils.py for test of PathUtils functions.
I also updated Changelog.

2020-11-12 17:04 UTC, wtdcode commented
Hi!

Glad to see your PR. I will review it tomorrow.

2020-11-13 09:27 UTC, wtdcode requested changes

2020-11-13 09:27 UTC, wtdcode commented on qiling/os/utils.py
> +        sep = path._flavour.sep
Quite tricky here. But it seems that we can't find a better approach. I suggest adding a dict like:

```python
seps = {
PureWindowsPath : "\\"
...
}
```

2020-11-13 09:27 UTC, wtdcode commented on qiling/os/utils.py
> +            normalized_path += sep + name
Why not pathlib here? Manual path concatenation often leads to critical bugs.

2020-11-13 09:27 UTC, wtdcode commented
Note that please also resolve the conflicts.

2020-11-13 14:38 UTC, nmantani commented
Thank you for your review! I resolved conflict of Changelog.
I will rewrite normalize() function based on your advice.

2020-11-13 16:05 UTC, nmantani commented
I have rewritten normalize() function and manual path concatenation is eliminated.
Please check it.

2020-11-13 16:26 UTC, wtdcode commented
Looks good now. Thanks for your fix!

2020-11-13 16:26 UTC, merged